FROM imbios/bun-node:20-slim

WORKDIR /app

COPY package.json bun.lockb ./

RUN bun install --production --frozen-lockfile

COPY . .

ARG NODE_ENV
ARG AUTH_URL
ARG AUTH_SECRET
ARG AUTH_GOOGLE_ID
ARG AUTH_GOOGLE_SECRET
ARG AUTH_GITHUB_ID
ARG AUTH_GITHUB_SECRET
ARG OPEN_WEATHER_API_KEY

ENV SKIP_ENV_VALIDATION=true
ENV NODE_ENV=${NODE_ENV}
ENV AUTH_URL=${AUTH_URL}
ENV AUTH_SECRET=${AUTH_SECRET}
ENV AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
ENV AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
ENV AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
ENV AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}
ENV OPEN_WEATHER_API_KEY=${OPEN_WEATHER_API_KEY}

RUN bun run build

EXPOSE 3000

ENTRYPOINT [ "bun", "run", "start" ]
