services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
      s3:
        condition: service_healthy
    restart: unless-stopped
    # networks:
    #   - nginx_default
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $DATABASE_USER -d $DATABASE_NAME']
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 5432:5432
    # networks:
    #   nginx_default:
    #     aliases:
    #       - globehub-db
  s3:
    image: bitnami/minio:2024
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${STORAGE_USER}
      MINIO_ROOT_PASSWORD: ${STORAGE_PASSWORD}
      MINIO_DEFAULT_BUCKETS: ${STORAGE_NAME}
    volumes:
      - ./data/s3:/bitnami/minio/data
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 2
    ports:
      - 9000:9000
    # networks:
    #   nginx_default:
    #     aliases:
    #       - globehub-s3
networks:
  nginx_default:
    external: true
