services:
  app:
    restart: unless-stopped
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
    depends_on:
      - db
      - s3
    ports:
      - '3069:3000'
  db:
    restart: unless-stopped
    image: postgres:15
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - '5469:5432'
  s3:
    restart: unless-stopped
    image: bitnami/minio:2024
    environment:
      MINIO_ROOT_USER: ${STORAGE_USER}
      MINIO_ROOT_PASSWORD: ${STORAGE_PASSWORD}
      MINIO_DEFAULT_BUCKETS: ${STORAGE_NAME}
    volumes:
      - ./data/s3:/bitnami/minio/data
    ports:
      - '9069:9000'
